### ISSUE TITLE
Limit and Range chart price draggers should pin to the tick grid when being dragged

### ISSUE THREAD

**Issue by Mister-Meeseeks** [CrocSwap/ambient-ts-app#1746]
Consider when the user is dragging the price selector bars in the chart, in either Limit or Range mode. Currently as they move their cursor up and down, the selector line moves smoothly and exactly with their cursor. This means as they drag, the dragger can be at a Y position that does not conform to a valid tick grid point:
<img width="711" alt="Screenshot 2023-04-06 at 1 16 46 AM" src="https://user-images.githubusercontent.com/18204987/230278292-aa16984e-569f-41b4-90ee-bac81fd71d7b.png">

Change this behavior so that the dragger line is always pinned to the closest tick grid point. As the user moves the cursor, the line should stay pinned until the Y-position of the cursor is closer to the next grid value, then the line should immediately snap to that grid point.

**Comment by PaulMcInnis** [comment]
relates to #2215

**Comment by surudhb** [comment]
We currently have the desired behaviour on the range module and would like the same for the limit module.

Range:
https://github.com/CrocSwap/ambient-ts-app/assets/45405267/816894ca-6034-4ad6-b052-a30f95560392

Limit:
https://github.com/CrocSwap/ambient-ts-app/assets/45405267/8db636d6-c212-47d5-ac5f-02a2c2d0af08
