### ISSUE TITLE
Don't show liquidity curve tooltip in sections with 0 dollars

### ISSUE THREAD

**Issue by Mister-Meeseeks** [CrocSwap/ambient-ts-app#1830]
In the liquidity curve popup, we shouldn't show any point that would register as $0 or 0%. Example of current behavior is below:

<img width="245" alt="Screenshot 2023-04-13 at 7 06 19 PM" src="https://user-images.githubusercontent.com/18204987/231901708-5545feaf-84aa-4194-98d6-5a6198b53340.png">

If a point would display 0 value, simply don't show the popup.

**Comment by PaulMcInnis** [comment]
doesn't show up in production (mainnet)
