### ISSUE TITLE
[Tech Debt]: Get Chat ready for Launch

### ISSUE THREAD

**Issue by c33cheun** [CrocSwap/ambient-ts-app#2135]
### What is needed?

- [ ] Identify issues with Chat
- [ ] Prioritize what is most important for bringing Chat to launch readiness
- [ ] Deliver high priority issues/fixes

**Comment by PaulMcInnis** [comment]
@miyuki-eto lmk if any of the above weren't addressed between this time and when we launched

**Comment by miyuki-eto** [comment]
it doesnt look like any of these have been addressed (checked on develop)

embeds no longer seem to come through at all. which tbh is preferred over having them half work

**Comment by PaulMcInnis** [comment]
Ok, ill make sure the work needed gets captured this time 👍
