### ISSUE TITLE
[Tech Debt]: consistent names between codebase and DOM

### ISSUE THREAD

**Issue by emilydrakesmith** [CrocSwap/ambient-ts-app#2179]
### What is needed?

There are a few cases where we've changed verbiage in the user-facing app but haven't updated the underlying functional code in the codebase to reflect. Examples:
* The page file `Range.tsx` renders the **Pool** page at the `/trade/range` URL path. (note: this change could affect chart functionality as the chart relies on the URL to determine which module is active)
* The page file `Portfolio.tsx` renders the **Account** page at the `/account` URL path.

Top priority is that no page given a colloquial name in the DOM should render at a URL path with an alternate name. This invites user confusion. **This part MUST be completed before we launch because once we're out, we're married to ongoing support of URL paths.**

Second priority is that page files should be named consistently with the pages they render. If we have a page colloquially named **Pool**, React convention is to have that page rendered by a file `Pool.tsx` in the `/src/pages` directory path.

Third priority is to update function names, variable names, etc where relevant. It isn't necessary to strike every instance of the word "range" from the app, but a hypothetical fn `goToRangePage()` should be renamed.

**Comment by Mister-Meeseeks** [comment]
Current URLs are now lindy, and no user has noticed any user issue. Since we've been live for weeks. Don't want to break anyone who has urls in history.
