### ISSUE TITLE
Chart loading screen should be replaced with the Ambient spinner

### ISSUE THREAD

**Issue by Mister-Meeseeks** [CrocSwap/ambient-ts-app#2213]
Current the loading screen for the chart component uses a Fetching message like this:

<img width="1112" alt="Screenshot 2023-05-24 at 12 31 58 AM" src="https://github.com/CrocSwap/ambient-ts-app/assets/18204987/188567b3-74b3-4423-8b9f-2200d777fecd">

It should be replaced with the Ambient snake eating its own tail spinner, like in the confirm modal:

<img width="414" alt="Screenshot 2023-05-23 at 11 57 30 PM" src="https://github.com/CrocSwap/ambient-ts-app/assets/18204987/a226bf2a-b6e4-46e3-a8bb-f262e275abfa">

**Comment by emilydrakesmith** [comment]
> It should be replaced with the Ambient snake eating its own tail spinner, like in the confirm modal:

FYI: "ouroboros" https://en.wikipedia.org/wiki/Ouroboros
