### ISSUE TITLE
[Enhancement]: Add schema validation and data logging to front-end via `useDebugValue`

### ISSUE THREAD

**Issue by emilydrakesmith** [CrocSwap/ambient-ts-app#2246]
### Requirements

The Ambient UI is a front-end only app but highly dependent on data served by our cache server. Since our app is growing quickly and will continue to do so for the foreseeable future, data schemas are frequently altered and expanded. This can cause development friction if the cache server has changes that change the shape of the data being served to the UI.

There exists a react hook called `useDebugValue()` which similar to an embedded version of `console.debug`. It runs top-level in React functions and custom hooks and can output data to the react browser dev tools. This is a convenient way to leave code _in situ_ in the app to present raw data to the dev team without gatekeeping by environmental variables but out of the way of common users unless they dig very deep monitoring app activity through dev tools.

For all async data queries from the front to external data sources, both ones we control and ones we don't, we should add logic with `useDebugValue()` to:
1. Render raw data in dev tools for debugging
2. Subject data to schema validation and flag data received which does not conform to the expected shape

This will allow much faster debugging of issues in the front when the UI reacts unexpectedly in response to data received by the back. With no additional coding, we can evaluate the data received by the front and determine whether it was received in a malformed state or whether the front itself has a bug in proper handling.

https://react.dev/reference/react/useDebugValue

### Figma

n/a

**Comment by Mister-Meeseeks** [comment]
Backend already has a schema validation infrastructure to detect issues. Given that this would only be useful for the backend schema drifting from the Typescript interfaces in the frontend. This was more of an issue before transition to gcgo, but now backend data uses minimally decorated, small objects that largely don't change over time. Therefore this issue should be shelved until if/when frontend schema drift becomes a pain point.
