### ISSUE TITLE
[Bug]: Transactions not appearing after submission/confirmation

### ISSUE THREAD

**Issue by enwong10** [CrocSwap/ambient-ts-app#2329]
Previously had a feature where as soon as you send the order, it appears in the table with blanked out quantities, then once its confirmed it fills in the blank details

If i refresh the page the tx appears in the table

Likely caused by regression

**Comment by benwolski** [comment]
This can go on the backlog, maybe more appropriately as an enhancement ticket to add a visual indicator of a pending transaction local to the user's browser. The previous solution to use the graph cache server to track pending transactions is no longer in use due to server changes.

**Comment by surudhb** [comment]
closing in favor of https://github.com/CrocSwap/ambient-ts-app/issues/2696
