### ISSUE TITLE
Confirmation Modal UI/UX changes 

### ISSUE THREAD

**Issue by enwong10** [CrocSwap/ambient-ts-app#2345]
- [ ] Remove top price field
- [ ] Inconsistent padding

https://www.notion.so/crocswap/FE-review-02-06-23-b151fe1c7091447d9c7ce809fbff993b?pvs=4 for more details

**Comment by surudhb** [comment]
@miyuki-eto are the price fields referring to the eth and usd fields on the confirmation modal? we don't see the actual amount of tokens in the extra info anymore. do we still want to remove the price fields?

<img width="565" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/45405267/bd6bc9fd-2b15-4068-9365-51cf6166871a">


<img width="432" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/45405267/91ebe0fb-f63e-4d8c-80ba-6b730e5361e5">

**Comment by surudhb** [comment]
closing this as the current modal looks good
