### ISSUE TITLE
FE component overhaul 

### ISSUE THREAD

**Issue by enwong10** [CrocSwap/ambient-ts-app#2391]
Investigate memoizing components directly: https://react.dev/reference/react/memo#updating-a-memoized-component-using-a-context

Split up contexts: 
- App State context should be as small as possible 
- Global modal implementation can be replaced with createPortal 
- The ultimate goal is to have as many contexts wrap specific components as possible, to avoid full app rerender 

This should be done in with https://github.com/CrocSwap/ambient-ts-app/issues/2137

**Comment by surudhb** [comment]
done with #2137 and others
