### ISSUE TITLE
[Enhancement]: Show origin token lists in token selector modal

### ISSUE THREAD

**Issue by emilydrakesmith** [CrocSwap/ambient-ts-app#2463]
### Requirements

Our app uses token lists to generate clickables for users to select a token in the DOM, and also sources token data directly from on-chain queries such that users can import custom unlisted tokens to the app.

Though the token selector modal in the UI promotes tokens in search results per secondary endpoints suggesting they are likely to be the genuine, canonical token being sought, it's possible for two tokens to appear in the DOM with similar (or identical) names, logos, and symbols. This is especially true if the user imports a scam token.

The token selector modal, on each token clickable, should display the source(s) any given token data object originated.

Examples:
* _Listed by Ambient, Coingecko, and n others_
* _Listed by Coingecko and Uniswap_
* _Listed by Coingecko_
* _Imported by user_ (unlisted tokens only)

As of PR #2422 the relevant data is available in place in the DOM. We need a mockup from the Product team showing:
1. How this data should be shown in the DOM
2. Text gen templates for different data counts (eg 3 lists, 2 lists, etc)

Per Doug this is not a priority for the launch version of the app.

**Comment by miyuki-eto** [comment]
added the scrollbar to the mockup located here - https://www.figma.com/file/0ItLk4nJmtj741R8sn3HYp/ambient?type=design&node-id=26%3A2931&mode=design&t=vbPaV510BDTyc1S2-1 (there is a preview below it you can view in present mode)

regarding the amounts in wallet - 
1. i seem to remember from the product meeting that this is easily added
2. ideally if the amount is 0 it would be represented with a dash '-'. i just think this will reduce the visual weight of having hundreds of 0's - not a huge priority if its an issue

let me know if any other design aspects are required to be mocked up

**Comment by Mister-Meeseeks** [comment]
Not necessary at current time, since tokens are sorted.
