### ISSUE TITLE
[Enhancement]: Add Analytics Page

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/ambient-ts-app#2576]
### Requirements

- [ ] - Top Nav link to Analytics at /analytics
- [ ] - Sidebar link to analytics at end of Top Pools section of sidebar
- [ ] - retrieve list of most recently used pools (e.g. https://ambindexer.net/gcgo/pool_list?chainId=0x1&poolIdx=420)
- [ ] - filter pool_list results by chainId active in the UI ([gcgo issue #6](https://github.com/CrocSwap/graphcache-go/issues/6))
- [ ] - retrieve TVL / Volume for each pool (similar to Top Pools cards)
- [ ] - retrieve current pool price and 24h change percentage (similar to Top Pools cards on homepage)
- [ ] - display a row containing the above information and a link to /trade/market route for each pool in pool_list
- [ ] - highlight each row on hover (similar to trade/portfolio tables)
- [ ] - enabled sorting by TVL, Volume, Price, Price Change %
- [ ] - add 'View more' link on homepage (as pictured below)

![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/c29d17e2-c5f8-42e4-a187-5b0766fadae2)

![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/5c987f8e-1fd3-46ae-9661-91068f6eaf00)

### Figma

https://www.figma.com/proto/0ItLk4nJmtj741R8sn3HYp/ambient?type=design&node-id=6406-152220&t=oYfxxDdr0b3jq5sV-0&scaling=min-zoom&page-id=4359%3A117444&starting-point-node-id=4378%3A105457&show-proto-sidebar=1

**Comment by PaulMcInnis** [comment]
NOTE: risk of unacceptable # of infura calls, may need to add cached endpoint for pool stats

**Comment by PaulMcInnis** [comment]
@miyuki-eto need some mockups for view more link (top pools) on homepage

**Comment by emilydrakesmith** [comment]
> NOTE: risk of unacceptable # of infura calls, may need to add cached endpoint for pool stats

I added logic to gatekeep the one automated call. All unguarded calls are made on explicit user action. I did open the gate if the call errors but we'll adjust later if that happens.

![image](https://github.com/CrocSwap/ambient-ts-app/assets/71150790/b58b62bd-cfce-42af-8d6d-b019b397d1ee)
![image](https://github.com/CrocSwap/ambient-ts-app/assets/71150790/c9e53588-871f-4ff7-8b29-8c70b1999547)
