### ISSUE TITLE
[Enhancement]: Chat Embed Support

### ISSUE THREAD

**Issue by PaulMcInnis** [CrocSwap/ambient-ts-app#2584]
### Requirements

- [ ] sell orders dont come through the same as buy orders. when you paste in the tx id, a buy order will convert to the nice embedded card, but sell orders do not
- [ ] ranges also do not come through as embeds

relates to #2135

**Comment by surudhb** [comment]
Blocked on https://github.com/CrocSwap/graphcache-go/issues/3
