### ISSUE TITLE
[Enhancement]: Chat colouration

### ISSUE THREAD

**Issue by PaulMcInnis** [CrocSwap/ambient-ts-app#2585]
### Requirements

- [ ] update the buy and sell colours to match the updated ones in the trade table (buys are primary light and sells are primary)
- [ ] the arrow drop down icon on the chat select box needs vertical aligning to the center

relates to #2135

**Comment by surudhb** [comment]
<img width="470" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/45405267/5329e9cb-4e82-415c-af86-b7c67b4f2bd2">
look for figma as well

**Comment by benwolski** [comment]
closing and referencing issue in #2797
