### ISSUE TITLE
[Enhancement]: User should be able to paginate pool list

### ISSUE THREAD

**Issue by yharsono** [CrocSwap/ambient-ts-app#2612]
### Requirements

User should be able to select how many pool list at a time
User should be able to move between previous and the next page

This pagination component should be reusable for other type of list

**Comment by emilydrakesmith** [comment]
> This pagination component should be reusable for other type of list

We have a `usePagination()` hook which is set up to run as a generic. Can paginate data regardless of its shape.

**Comment by benwolski** [comment]
API is currently returning 50. We would like to eventually show all 50, but it's limited to 20 for now.

**Comment by benwolski** [comment]
we've decided to show all 50 in a scrollable list, rather than paginate
