### ISSUE TITLE
[Tech Debt]: Remove instances of using the DOM to get/set input values 

### ISSUE THREAD

**Issue by surudhb** [CrocSwap/ambient-ts-app#2617]
### What is needed?

- We should be using our state management to modify the contents of input fields across the app.
- There are instances where we use the DOM to manually set certain inputs' values. We should instead have a state variable to track what these fields should look like
- Can search the codebase for `as HTMLInputElement` as a starting point

<img width="438" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/45405267/2feea579-181e-4c61-b081-45beb526fa95">
<img width="392" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/45405267/c8a82bfe-5fcc-400f-923a-ece74fb6c7c3">

**Comment by emilydrakesmith** [comment]
I agree with this goal but looking over the codebase, we have a number of processes using direct DOM manipulation and we're probably better-served addressing them in isolation. I'm closing this ticket and will reorganize it as a project with more granular divisions.
