### ISSUE TITLE
[Enhancement]: Create the info tab for the transaction tables

### ISSUE THREAD

**Issue by Jadessu** [CrocSwap/ambient-ts-app#2619]
### Requirements

Create the info tab for the transaction tables:
<img width="937" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/83131501/bfba8727-20cb-4cde-b57e-91131efa949c">

### Figma

https://www.figma.com/file/0ItLk4nJmtj741R8sn3HYp/ambient?type=design&node-id=520-30322&mode=dev

**Comment by PaulMcInnis** [comment]
NOTE: will create endpoint for this in audit server https://github.com/hyplabs/crocswap_audit_tools/issues/46
