### ISSUE TITLE
[Bug]: Exchange balance pop-up disappears after user selects text in input field

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/ambient-ts-app#2628]
### What happened?

![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/c032684b-bdec-4dda-8827-b37ec5df6199)

### How?

If you use your mouse to select the text and do not mouse up before the cursor leaves the boundaries of the pop-up, then the pop-up disappears on mouse-up.

### What was Expected?

The pop up should only disappear when the user initiates a click (mousedown) outside the pop-up, and should not disappear when the click started inside the pop-up.

**Comment by surudhb** [comment]
Seeing this behaviour on the other dropdown items as well. If the mouseup occurs outside, the dropdowns close automatically
