### ISSUE TITLE
[Enhancement]: Consolidate Confirm[Swap,Limit,Range,Reposition]Modal

### ISSUE THREAD

**Issue by surudhb** [CrocSwap/ambient-ts-app#2643]
### Requirements

Investigate and consolidate as much of the shared aspects of these components and their css.

**Comment by enwong10** [comment]
Closing as will not complete after investigation

**Comment by surudhb** [comment]
re-opening to capture updates made to the usage of these modals. note: no css was consolidated as part of the ticket
