### ISSUE TITLE
[Bug]: Resolve infinite loading on chart when there is no candle data

### ISSUE THREAD

**Issue by surudhb** [CrocSwap/ambient-ts-app#2652]
### What happened?

Chart stuck in infinite loading state

<img width="1429" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/45405267/6e50e6c2-4777-42d8-bce8-2caf7d42f882">

### How?

On mainnet, select ETH/PEPE as the token pair and use any time lookback <= 1h (The bug does not occur on 4h, 1 day because there is candle data)

### What was Expected?

Show the empty state for the chart

**Comment by emilydrakesmith** [comment]
redundant with #2630
