### ISSUE TITLE
[Bug]: Wallet options in order input not being recalled from local storage

### ISSUE THREAD

**Issue by miyuki-eto** [CrocSwap/ambient-ts-app#2675]
### What happened?

The web app does not remember wallet preferences upon switching order type or page etc. 

![brave_jaTzPi5XE2](https://github.com/CrocSwap/ambient-ts-app/assets/82160202/41732ae6-c492-4ec8-a196-b3917fd54b8a)

### How?

navigate to the `/swap` or `/trade` page, any order type, change the wallet option from exchange balance to wallet, or vice versa. then change the order type, and switch back. 

### What was Expected?

the wallet selection preference would be saved and recalled from local storage so its persistent 

### What browser(s) are you seeing the problem on?

Brave Browser

**Comment by surudhb** [comment]
looks like the wallet selection on the active input is the one not being saved

**Comment by benwolski** [comment]
The app is currently functioning as expected:

- Swap output preference is stored and initialized from local storage
- Swap/limit/range input  preference is determined dynamically based on whether the user has a non-zero dex balance
