### ISSUE TITLE
[Enhancement]: New cover image

### ISSUE THREAD

**Issue by surudhb** [CrocSwap/ambient-ts-app#2693]
### Requirements

- the current one looks a little low quality so i upscaled it and changed it a bit

### Figma

https://www.figma.com/file/0ItLk4nJmtj741R8sn3HYp/ambient?type=design&node-id=6555%3A116028&t=SqjZHs8Aj0tQbDRg-1

**Comment by PaulMcInnis** [comment]
relates to #2539

**Comment by PaulMcInnis** [comment]
use SVG format to avoid image size issues
