### ISSUE TITLE
[Bug]: Temporarily remove all translations

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/ambient-ts-app#2697]
### What happened?

The translations for Chinese and Korean are incomplete. let's remove then until the translations are complet.

### How?

?

### What was Expected?

?

**Comment by surudhb** [comment]
update: we decided to leave in the translations logic but force it to US - English for now to be consistent with the approach we've taken for token formatting. As part of a larger effort later, internationalization can be added throughout the app
