### ISSUE TITLE
[Bug]: Fix over-rendering issue on /explore

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/ambient-ts-app#2717]
### What happened?

block updates appear to be triggering re-renders of the Top Pools table on /explore even though the data is only updated manually.

### How?

navigate to /explore and run react developer tools to observe re-renders

### What was Expected?

re-renders only when the user triggers a data update

**Comment by PaulMcInnis** [comment]
relates to #2678

**Comment by emilydrakesmith** [comment]
Re-renders of `Explore.tsx` are a downstream effect of `App.tsx` re-rendering. I've confirmed that none of the data flowing into `Explore.tsx` is changing (including specious cases of an object being re-written to a new address in memory). Every instance of `Explore.tsx` re-rendering immediately follows a case of `App.tsx` re-rendering on a 1:1 basis. No new expensive data fetching occurs on re-renders.
