### ISSUE TITLE
[Bug]: Reversing tokens via the selector when the chart is loading does nothing

### ISSUE THREAD

**Issue by enwong10** [CrocSwap/ambient-ts-app#2734]
### What happened?

Reversing tokens via the selector when the chart is loading does nothing

### How?

1. Navigate to trade route 
2. While the chart is still loading, reverse the tokens *via the token selector*
3. Nothing happens

### What was Expected?

Tokens are reversed

**Comment by surudhb** [comment]
NOTE: the token selector does show a loading indicator but at times, the loading indicator does dissapear before the chart finishes loading giving the impression that the tokens are indeed swappable
