### ISSUE TITLE
[Bug]: Token selector shows the fallback icon for a token with an icon when switching from a token without an icon

### ISSUE THREAD

**Issue by surudhb** [CrocSwap/ambient-ts-app#2759]
### What happened?

Incorrect token icons displayed

https://github.com/CrocSwap/ambient-ts-app/assets/45405267/c5b98706-3b2c-4da4-a475-2913ebd553c2

### How?

- Select a pair of tokens that do not have a pool initialized (one of the tokens must use the default token icon)
- Click "No, take me back" 
- See the token icons not being updated correctly

OR

- Select a token using a fallback icon
- switch to a token with a proper icon

### What was Expected?

Correct token icons displayed

**Comment by enwong10** [comment]
Unable to reproduce

**Comment by benwolski** [comment]
possible duplicate
