### ISSUE TITLE
[Bug]: Pool width cursor 

### ISSUE THREAD

**Issue by enwong10** [CrocSwap/ambient-ts-app#2779]
### What happened?

Pool width cursor makes it look clickable
- Est. APR
- Current Price

![image](https://github.com/CrocSwap/ambient-ts-app/assets/32200626/e16250fe-8c59-4eb0-899b-c6d353fd07cc)

### How?

Hover over the label on the rows 

### What was Expected?

Cursor: Pointer

**Comment by benwolski** [comment]
these values have been removed entirely
