### ISSUE TITLE
[Bug]: Left side of Add button is sometimes not clickable

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/ambient-ts-app#2786]
### What happened?

Clicking the left side of the Add button (at a screen width like shown below) will not trigger the Add action, but rather trigger the range details modal to open.

![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/ed01858c-6b3a-4668-9904-697b34326935)

### How?

adjust screen width like shown below

### What was Expected?

the Add function should get triggered, rather than the modal opening

**Comment by enwong10** [comment]
This is because the width of the left column covers up the Add button, despite it overflowing - should be fixed by https://github.com/CrocSwap/ambient-ts-app/issues/2689
