### ISSUE TITLE
[Tech Debt]: make `handleWETH.ts` extensible across multiple chains

### ISSUE THREAD

**Issue by emilydrakesmith** [CrocSwap/ambient-ts-app#2831]
### What is needed?

The file `handleWETH.ts` is configured to detect user search input indicating WETH token return a message encouraging the user to transact on ETH instead. This should be refactored to handle the same relationship between the native and wrapped forms of a token on other chains as well.

The base logic isn't complicated but is simplified by being able to hardcode the names and symbols of the native and wrapped-version native (`'Native Ether'` + `'ETH'` vs `'Wrapped Ether'` + `'WETH'`, respectively). To satisfy single source of truth code standards, these tokens should be defined through address constants that pass into the `wrappedNatives.ts` wrapper. However, getting the full name and symbol of the token will need to rely on accessing live data in the `useTokens.ts` hook. This will mean un-abstracting the logic from the `handleWETH.ts` file to a place it can access data and methods from `useTokens()`, most likely in the `TokenContext.tsx` context file.

**Comment by benwolski** [comment]
may be related to https://github.com/CrocSwap/ambient-ts-app/pull/3041
