### ISSUE TITLE
[L2]: Investigate FE dependencies and assumptions

### ISSUE THREAD

**Issue by enwong10** [CrocSwap/ambient-ts-app#2934]
### Requirements

Currently, there are hardcoded assumptions and logic written solely for mainnet/testnet that need to abstracted. This ticket is for finding all of these places and noting them down [here](https://www.notion.so/hypotenuselabs/FE-Investigation-Doc-c7c6e39c9be948fbb6fc14317b9ebfa8). This is purely an investigation ticket, there should be **no code changes**

**Comment by benwolski** [comment]
we'll need to update the block time estimates used to generate the '[n] minutes/hours/days ago' Timestamp values displayed to the user in the tables and notification center
