### ISSUE TITLE
[Tech Debt]: Add IDs to page elements for easier automated testing

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/ambient-ts-app#3067]
### What is needed?

It would be helpful to have unique IDs for various user interface elements, including table rows and those elements depicted in the attached document.

[ID Fields.docx](https://github.com/CrocSwap/ambient-ts-app/files/13071660/ID.Fields.docx)

![image](https://github.com/CrocSwap/ambient-ts-app/assets/570819/5ac2f6ca-d869-42ce-97a6-2c4ffb33d295)

**Comment by emilydrakesmith** [comment]
W3 convention is that element IDs must be globally unique to the document, not to the app. When we render the same item on multiple pages do we expect it to have the same ID attribute on both?
