### ISSUE TITLE
[Enhancement]: add link between crocswap.com and ambient.finance

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/ambient-ts-app#3123]
### Requirements

each of the websites should have a link to the other

crocswap.com
ambient.finance

**Comment by emilydrakesmith** [comment]
We should also discuss how `crocodilelabs.io` plays into the mix.

**Comment by emilydrakesmith** [comment]
Issue is iceboxed pending internal discussions on long-term brand strategy and how to leverage our various web assets.
