### ISSUE TITLE
[Enhancement]: adjust icons for resource links

### ISSUE THREAD

**Issue by emilydrakesmith** [CrocSwap/ambient-ts-app#3163]
### Requirements

The in-app menu to resource links (internal and external) is shown below.
1. The **Docs** link uses an icon which is stylistically inconsistent with the others (outline rather than solid-fill)
2. The **Privacy** and **Terms of Service** links both use the same icon which is fairly generic

Additionally, three items in the footer of the index page don't have icons but the others do. Items missing an icon are:
1. **Terms of Service**
2. **Privacy Policy**
3. **Docs**

We should choose a new icon for **Docs** which is stylistically-consistent with the other icons and change one or both icons currently used for **Privacy** and **Terms of Service**. We should also choose icons for the icon-less items in the index page footer. Lastly, we should ensure that resources linked in both the menu and the index page footer use consistent iconography (eg, **Terms of Service** should use the same icon in both locations, adjusted for size).

@miyuki-eto We already have [every icon from this package](https://react-icons.github.io/react-icons/) on board if you'd like to choose new options

### In-App Resource Menu:
<img width="1837" alt="Ambient | Zero-to-One Decentralized Trading Protocol 2023-10-27 14-33-39" src="https://github.com/CrocSwap/ambient-ts-app/assets/71150790/ca0f2ee8-c639-45c1-8765-59d81c6f5288">

### Footer of index page:
<img width="1097" alt="image" src="https://github.com/CrocSwap/ambient-ts-app/assets/71150790/cb7f7740-6afc-48ad-ad08-afe346284f51">

**Comment by miyuki-eto** [comment]
using the react-icons pack -

docs icon - SiGitbook
privacy icon - RiSpyFill
terms of service icon can stay as the one in the burger menu

and the footer icons can match those listed above

also do we require the about us section in the footer?

**Comment by emilydrakesmith** [comment]
@miyuki-eto Not necessary to include the **About Us** link, this was a request from Ben I've been working on for a few days (along with some related code cleanup). That said, I do generally agree that if we have multiple web properties it's good practice for them to cross-link each other to indicate they come from the same organization.
